# Generated by Django 4.2.17 on 2025-01-11 22:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cartas/')),
                ('type', models.CharField(choices=[('SKIP', 'Saltar turno'), ('SUPER_SKIP', 'Saltar turnos'), ('DEFUSE', 'Desactivar bomba'), ('EXPLODING_KITTEN', 'Exploding Kitten'), ('SEE_THE_FUTURE_3', 'Ver el futuro'), ('SEE_THE_FUTURE_5', 'Ver el futuro'), ('ALTER_THE_FUTURE_3', 'Ver el futuro'), ('ALTER_THE_FUTURE_5', 'Ver el futuro por 5'), ('ATTACK', 'Atacar'), ('NOPE', 'Nope'), ('CATOMIC_BOMB', 'Bomba atomica'), ('BLIND', 'Cegar'), ('DRAW_FROM_THE_BOTTOM', 'Agarrar desde abajo'), ('REVEAL_THE_FUTURE', 'Revela el futuro'), ('SHUFFLE', 'Mezclar cartas'), ('TACOCAT', 'Carta para robar')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('max_players', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(through='game.PlayerRoom', to='social.player')),
            ],
        ),
        migrations.AddField(
            model_name='playerroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='social.player')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField(default=list)),
                ('discarded', models.JSONField(default=list)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
