# Generated by Django 4.2.17 on 2025-01-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_setting_player_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default/avatar_default.png', null=True, upload_to='profile_pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
